mas ajustes

diff --git a/.github/workflows/publissh.yml b/.github/workflows/publissh.yml
--- a/.github/workflows/publissh.yml
+++ b/.github/workflows/publissh.yml
@@ -81,6 +81,15 @@ jobs:
           sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose
 
+      # Verificar si Docker Compose está instalado correctamente
+      - name: Verify Docker Compose installation
+        run: |
+          docker-compose --version
+          if [ $? -ne 0 ]; then
+            echo "Docker Compose installation failed"
+            exit 1
+          fi
+
       - name: Set up deployment directory
         run: |
           mkdir -p ~/.ssh
@@ -122,6 +131,15 @@ jobs:
         run: |
           sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose
+
+      # Verificar si Docker Compose está instalado correctamente
+      - name: Verify Docker Compose installation
+        run: |
+          docker-compose --version
+          if [ $? -ne 0 ]; then
+            echo "Docker Compose installation failed"
+            exit 1
+          fi
 
       - name: Set up deployment directory
         run: |
